#+title: RedVEu (Redmine for VEuPath)
#+author: John Brestelli

* Getting started

** Requirements

=redveu= depends on the following emacs lisp packages, which are
available from MELPA.  Install these packages as well.
- [[https://github.com/leoc/elmine][elmine]] --- Redmine API access

** Download and put redveu.el to a directory in `load-path'.

** Edit your ~/.emacs

#+begin_src emacs-lisp
  ;; Change these as appropriate
  (add-to-list 'load-path "~/redmine/elmine")
  (add-to-list 'load-path "~/redmine/redveu")

  (load "redveu")
  (setq elmine/host "https://redmine.apidb.org")
  (setq elmine/api-key "YOUR_API_KEY")
#+end_src

** Basics
   1. Project and issue queries must (for now) be created and saved using redmine's web interface
   2. Changes you make to the text in the org file will not be reflected in redmine.  To update tasks, you must run update commands
   3. You can search for issues using pre defined query
      #+begin_src emacs-lisp
      redveu/get-issues query_id
      #+end_src
   4. Search for projects using pre defined query
      #+begin_src emacs-lisp
      redveu/get-projects query_id
      #+end_src
   5. When cursor is on a project, get all project-issues using predefined query
      #+begin_src emacs-lisp
      redveu/get-project-issues query_id
      #+end_src
   6. When cursor is on an issue, get all comments associated with issue 
      #+begin_src emacs-lisp
      redveu/verbose-issue
      #+end_src
   7. Link to create new issue for a project
   8. Easily link to issue web page
   9. Link to create subtask of an issue
   10. Link to attachments
   11. when cursor is on an issue, update issues using api (PUT)
       #+begin_src emacs-lisp
       redveu/update-assigned-to
       redveu/update-status
       redveu/update-tracker
       redveu/update-priority
       redveu/update-subject
       redveu/add-comment
       #+end_src
       - can uses interactive autocomplete
       - fetches and caches available options (on first call)
       - add a comment/note or change subject

* TODOs
   1. Journals/Comments and Attachments are not automatically included when viewing issues.  you must ask for them
      #+begin_src emacs-lisp
      (redveu/verbose-issue)
      #+end_src
   2. Cannot update Custom Fields currently
      - https://redmine.apidb.org/api_custom_fields.json
      #+begin_example
      PUT /issues/296.json
      {"issue":
        {
        "subject":"Updating custom fields of an issue",
         ...
         "custom_fields":
          [
            {"value":"1.0.2","id":1},
            {"value":"Invalid","id":2}
          ]
        }
     }
      #+end_example

